import { Card } from "@/app/components/ui/card";
import { Button } from "@/app/components/ui/button";
import { Badge } from "@/app/components/ui/badge";
import { Input } from "@/app/components/ui/input";
import { Label } from "@/app/components/ui/label";
import { Separator } from "@/app/components/ui/separator";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/app/components/ui/table";
import { Copy, Check, ExternalLink } from "lucide-react";
import { useState } from "react";
import { toast } from "@/app/lib/toast";
import { copyToClipboard } from "@/app/lib/clipboard";

const referralData = {
  code: "KLINEO-XYZ123",
  link: "https://klineo.xyz/ref/XYZ123",
  tier1Earnings: 1275.50,
  tier2Earnings: 342.80,
  pendingEarnings: 85.00,
  paidEarnings: 1533.30,
};

const earningsHistory = [
  { user: "user_abc***", tier: 1, platformFee: 45.20, commission: 10, amount: 4.52, status: "Paid" },
  { user: "user_def***", tier: 1, platformFee: 32.80, commission: 10, amount: 3.28, status: "Paid" },
  { user: "user_ghi***", tier: 2, platformFee: 28.40, commission: 5, amount: 1.42, status: "Paid" },
  { user: "user_jkl***", tier: 1, platformFee: 52.10, commission: 10, amount: 5.21, status: "Pending" },
  { user: "user_mno***", tier: 2, platformFee: 19.70, commission: 5, amount: 0.99, status: "Pending" },
];

interface ReferralsProps {
  onNavigate: (view: string) => void;
}

export function Referrals({ onNavigate }: ReferralsProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const handleCopy = (text: string, type: string) => {
    copyToClipboard(text);
    setCopied(type);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold mb-1">Referrals</h1>
        <p className="text-sm text-muted-foreground">Earn commission from platform fees generated by your referrals</p>
      </div>

      {/* Referral Info */}
      <Card className="p-6 space-y-6">
        <div>
          <h3 className="text-lg font-semibold mb-4">Your Referral Details</h3>
          <div className="grid grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground uppercase tracking-wide">Referral Link</label>
              <div className="flex gap-2">
                <Input value={referralData.link} readOnly className="font-mono text-sm" />
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => handleCopy(referralData.link, "link")}
                >
                  {copied === "link" ? <Check className="size-4 text-[#10B981]" /> : <Copy className="size-4" />}
                </Button>
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground uppercase tracking-wide">Referral Code</label>
              <div className="flex gap-2">
                <Input value={referralData.code} readOnly className="font-mono text-sm" />
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => handleCopy(referralData.code, "code")}
                >
                  {copied === "code" ? <Check className="size-4 text-[#10B981]" /> : <Copy className="size-4" />}
                </Button>
              </div>
            </div>
          </div>
        </div>

        <div className="p-4 bg-secondary/30 rounded space-y-2">
          <h4 className="font-semibold text-sm">2-Tier Referral System</h4>
          <ul className="space-y-1 text-sm text-muted-foreground">
            <li>• <span className="text-primary font-medium">Tier 1 (10%)</span>: Earn 10% of platform fees from users you refer directly</li>
            <li>• <span className="text-primary font-medium">Tier 2 (5%)</span>: Earn 5% of platform fees from users referred by your referrals</li>
            <li>• Commission is funded exclusively from platform fee revenue</li>
            <li>• Minimum payout: $50.00 USDT</li>
          </ul>
        </div>
      </Card>

      {/* Earnings Summary */}
      <div className="grid grid-cols-4 gap-4">
        <Card className="p-4 space-y-2">
          <div className="text-xs text-muted-foreground uppercase tracking-wide">Tier 1 Earnings</div>
          <div className="text-2xl font-semibold text-primary">${referralData.tier1Earnings.toFixed(2)}</div>
          <div className="text-xs text-muted-foreground">10% commission</div>
        </Card>

        <Card className="p-4 space-y-2">
          <div className="text-xs text-muted-foreground uppercase tracking-wide">Tier 2 Earnings</div>
          <div className="text-2xl font-semibold text-primary">${referralData.tier2Earnings.toFixed(2)}</div>
          <div className="text-xs text-muted-foreground">5% commission</div>
        </Card>

        <Card className="p-4 space-y-2">
          <div className="text-xs text-muted-foreground uppercase tracking-wide">Pending Earnings</div>
          <div className="text-2xl font-semibold">${referralData.pendingEarnings.toFixed(2)}</div>
          <div className="text-xs text-muted-foreground">Awaiting settlement</div>
        </Card>

        <Card className="p-4 space-y-2">
          <div className="text-xs text-muted-foreground uppercase tracking-wide">Paid Earnings</div>
          <div className="text-2xl font-semibold text-[#10B981]">${referralData.paidEarnings.toFixed(2)}</div>
          <div className="text-xs text-muted-foreground">Total paid out</div>
        </Card>
      </div>

      {/* Earnings Table */}
      <Card>
        <div className="p-6 border-b border-border">
          <h3 className="text-lg font-semibold">Earnings History</h3>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Source User</TableHead>
              <TableHead>Tier</TableHead>
              <TableHead>Platform Fee Generated</TableHead>
              <TableHead>Commission %</TableHead>
              <TableHead>Commission Amount</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {earningsHistory.map((earning, i) => (
              <TableRow key={i}>
                <TableCell className="font-mono text-sm">{earning.user}</TableCell>
                <TableCell>
                  <Badge variant="outline" className={earning.tier === 1 ? "border-primary/50 text-primary" : ""}>
                    Tier {earning.tier}
                  </Badge>
                </TableCell>
                <TableCell className="font-mono">${earning.platformFee.toFixed(2)}</TableCell>
                <TableCell className="font-mono">{earning.commission}%</TableCell>
                <TableCell className="font-mono font-semibold text-primary">${earning.amount.toFixed(2)}</TableCell>
                <TableCell>
                  <Badge 
                    variant={earning.status === "Paid" ? "default" : "secondary"}
                    className={earning.status === "Paid" ? "border-[#10B981]/50 text-[#10B981] bg-[#10B981]/10" : ""}
                  >
                    {earning.status}
                  </Badge>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>

      {/* Payout Section */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Request Payout</h3>
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium mb-2 block">Payout Wallet Address</label>
              <Input placeholder="Enter USDT (TRC-20) wallet address" className="font-mono text-sm" />
              <p className="text-xs text-muted-foreground mt-1">Configure in Settings → Referral Payout Wallet</p>
            </div>
            <div className="p-4 bg-secondary/30 rounded">
              <div className="flex justify-between mb-2">
                <span className="text-sm text-muted-foreground">Available Balance:</span>
                <span className="font-mono font-semibold">${referralData.pendingEarnings.toFixed(2)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-muted-foreground">Minimum Payout:</span>
                <span className="font-mono">$50.00</span>
              </div>
            </div>
          </div>
          <div className="space-y-4">
            <Button 
              className="w-full bg-primary text-primary-foreground" 
              disabled={referralData.pendingEarnings < 50}
            >
              Request Payout
            </Button>
            <div className="text-xs text-muted-foreground space-y-1">
              <p>• Payouts processed within 24-48 hours</p>
              <p>• Minimum payout amount: $50.00 USDT</p>
              <p>• Ensure wallet address is correct before requesting</p>
            </div>
          </div>
        </div>
      </Card>

      {/* Payout History */}
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Payout History</h3>
        <div className="space-y-3">
          {[
            { date: "Jan 15, 2026", amount: "$250.00", status: "Completed", txHash: "0xabc...def" },
            { date: "Dec 10, 2025", amount: "$180.50", status: "Completed", txHash: "0x123...456" },
            { date: "Nov 05, 2025", amount: "$320.80", status: "Completed", txHash: "0x789...abc" },
          ].map((payout, i) => (
            <div key={i} className="flex items-center justify-between p-4 bg-secondary/30 rounded border border-border">
              <div>
                <div className="font-mono font-semibold mb-1">{payout.amount}</div>
                <div className="text-xs text-muted-foreground">{payout.date}</div>
              </div>
              <div className="flex items-center gap-4">
                <Badge variant="outline" className="border-[#10B981]/50 text-[#10B981]">
                  {payout.status}
                </Badge>
                <Button variant="ghost" size="sm" className="gap-1">
                  <span className="font-mono text-xs">{payout.txHash}</span>
                  <ExternalLink className="size-3" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}